#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Dec 08 20:55:34 CET 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_FV_GEMM_driver_behav -key {Behavioral:sim_1:Functional:tb_FV_GEMM_driver} -tclbatch tb_FV_GEMM_driver.tcl -log simulate.log"
xsim tb_FV_GEMM_driver_behav -key {Behavioral:sim_1:Functional:tb_FV_GEMM_driver} -tclbatch tb_FV_GEMM_driver.tcl -log simulate.log

